model:
    arch: pspnet
data:
    dataset: road
    train_split: train 
    val_split: val 
    img_rows: 1024
    img_cols: 1024
    path: /content/drive/My Drive/pytorch-semseg-master/ptsemseg/data
training:
    train_iters: 300000
    batch_size: 16
    val_interval: 1000 #?
    n_workers: 1 #?
    print_interval: 50 #?
    optimizer:
        name: 'adam'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:'constant_lr
    resume: 